# Generated by Django 2.2.28 on 2023-01-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictures',
            new_name='picture',
        ),
    ]
